version: 0.0.{build}-{branch}
branches:
  only:
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image: Visual Studio 2022

platform:
  - x64

configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

matrix:
  fast_finish: false

build:
  project: galaxy.sln