var hierarchy =
[
    [ "std::allocator< T >", null, null ],
    [ "galaxy::flags::AllowSerialize", "d4/dd3/structgalaxy_1_1flags_1_1AllowSerialize.html", null ],
    [ "galaxy::core::Application", "d5/da2/classgalaxy_1_1core_1_1Application.html", null ],
    [ "std::array< T >", null, null ],
    [ "std::array< float, 4 >", null, null ],
    [ "std::atomic< T >", null, null ],
    [ "std::atomic_ref< T >", null, null ],
    [ "galaxy::audio::AudioEngine", "d9/dbe/classgalaxy_1_1audio_1_1AudioEngine.html", null ],
    [ "std::auto_ptr< T >", null, null ],
    [ "std::basic_string< Char >", null, [
      [ "std::string", null, null ],
      [ "std::u16string", null, null ],
      [ "std::u32string", null, null ],
      [ "std::u8string", null, null ],
      [ "std::wstring", null, null ]
    ] ],
    [ "std::basic_string< char >", null, null ],
    [ "std::basic_string< char16_t >", null, null ],
    [ "std::basic_string< char32_t >", null, null ],
    [ "std::basic_string< char8_t >", null, null ],
    [ "std::basic_string< wchar_t >", null, null ],
    [ "std::basic_string_view< Char >", null, [
      [ "std::string_view", null, null ],
      [ "std::u16string_view", null, null ],
      [ "std::u32string_view", null, null ],
      [ "std::u8string_view", null, null ],
      [ "std::wstring_view", null, null ]
    ] ],
    [ "std::basic_string_view< char >", null, null ],
    [ "std::basic_string_view< char16_t >", null, null ],
    [ "std::basic_string_view< char32_t >", null, null ],
    [ "std::basic_string_view< char8_t >", null, null ],
    [ "std::basic_string_view< wchar_t >", null, null ],
    [ "galaxy::lua::BasicScript", "d4/d00/classgalaxy_1_1lua_1_1BasicScript.html", null ],
    [ "std::bitset< Bits >", null, null ],
    [ "std::bitset< GALAXY_FLAG_BITSET_COUNT >", null, null ],
    [ "galaxy::resource::Cache< Resource >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", null ],
    [ "galaxy::resource::Cache< audio::Sound >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Sounds", "dd/d48/classgalaxy_1_1resource_1_1Sounds.html", null ]
    ] ],
    [ "galaxy::resource::Cache< core::Prefab >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Prefabs", "d2/daf/classgalaxy_1_1resource_1_1Prefabs.html", null ]
    ] ],
    [ "galaxy::resource::Cache< graphics::Font >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Fonts", "df/d3d/classgalaxy_1_1resource_1_1Fonts.html", null ]
    ] ],
    [ "galaxy::resource::Cache< graphics::Shader >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Shaders", "d9/d24/classgalaxy_1_1resource_1_1Shaders.html", null ]
    ] ],
    [ "galaxy::resource::Cache< lua::BasicScript >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Scripts", "d8/d35/classgalaxy_1_1resource_1_1Scripts.html", null ]
    ] ],
    [ "galaxy::resource::Cache< tson::Map >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", [
      [ "galaxy::resource::Maps", "da/d87/classgalaxy_1_1resource_1_1Maps.html", null ]
    ] ],
    [ "galaxy::input::CameraKeys", "d0/d71/structgalaxy_1_1input_1_1CameraKeys.html", null ],
    [ "galaxy::graphics::Colour", "d2/dae/classgalaxy_1_1graphics_1_1Colour.html", null ],
    [ "Gfx::CompiledGeometryData", "d1/daa/structGfx_1_1CompiledGeometryData.html", null ],
    [ "std::complex", null, null ],
    [ "galaxy::core::Config", "d6/de9/classgalaxy_1_1core_1_1Config.html", null ],
    [ "std::wstring::const_iterator", null, null ],
    [ "std::map< K, T >::const_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_iterator", null, null ],
    [ "std::vector< T >::const_iterator", null, null ],
    [ "std::u8string::const_iterator", null, null ],
    [ "std::multimap< K, T >::const_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_iterator", null, null ],
    [ "std::u16string::const_iterator", null, null ],
    [ "std::set< K >::const_iterator", null, null ],
    [ "std::unordered_set< K >::const_iterator", null, null ],
    [ "std::multiset< K >::const_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_iterator", null, null ],
    [ "std::basic_string_view< Char >::const_iterator", null, null ],
    [ "std::u32string::const_iterator", null, null ],
    [ "std::array< T >::const_iterator", null, null ],
    [ "std::span< T >::const_iterator", null, null ],
    [ "std::string_view::const_iterator", null, null ],
    [ "std::wstring_view::const_iterator", null, null ],
    [ "std::u8string_view::const_iterator", null, null ],
    [ "std::u16string_view::const_iterator", null, null ],
    [ "std::u32string_view::const_iterator", null, null ],
    [ "std::basic_string< Char >::const_iterator", null, null ],
    [ "std::deque< T >::const_iterator", null, null ],
    [ "std::string::const_iterator", null, null ],
    [ "std::list< T >::const_iterator", null, null ],
    [ "std::forward_list< T >::const_iterator", null, null ],
    [ "std::forward_list< T >::const_reverse_iterator", null, null ],
    [ "std::wstring::const_reverse_iterator", null, null ],
    [ "std::map< K, T >::const_reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_reverse_iterator", null, null ],
    [ "std::u8string::const_reverse_iterator", null, null ],
    [ "std::multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::u16string::const_reverse_iterator", null, null ],
    [ "std::set< K >::const_reverse_iterator", null, null ],
    [ "std::unordered_set< K >::const_reverse_iterator", null, null ],
    [ "std::u32string::const_reverse_iterator", null, null ],
    [ "std::multiset< K >::const_reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_reverse_iterator", null, null ],
    [ "std::basic_string_view< Char >::const_reverse_iterator", null, null ],
    [ "std::array< T >::const_reverse_iterator", null, null ],
    [ "std::vector< T >::const_reverse_iterator", null, null ],
    [ "std::span< T >::const_reverse_iterator", null, null ],
    [ "std::string_view::const_reverse_iterator", null, null ],
    [ "std::wstring_view::const_reverse_iterator", null, null ],
    [ "std::u8string_view::const_reverse_iterator", null, null ],
    [ "std::u16string_view::const_reverse_iterator", null, null ],
    [ "std::basic_string< Char >::const_reverse_iterator", null, null ],
    [ "std::u32string_view::const_reverse_iterator", null, null ],
    [ "std::deque< T >::const_reverse_iterator", null, null ],
    [ "std::list< T >::const_reverse_iterator", null, null ],
    [ "std::string::const_reverse_iterator", null, null ],
    [ "galaxy::physics::Constants", "d4/d8a/structgalaxy_1_1physics_1_1Constants.html", null ],
    [ "galaxy::events::ContentScale", "d8/d2a/structgalaxy_1_1events_1_1ContentScale.html", null ],
    [ "galaxy::graphics::Camera::Data", "de/d59/structgalaxy_1_1graphics_1_1Camera_1_1Data.html", null ],
    [ "std::deque< T >", null, null ],
    [ "galaxy::doNotUseReferToConfigForMacroNames", "db/ddc/structgalaxy_1_1doNotUseReferToConfigForMacroNames.html", null ],
    [ "galaxy::flags::Enabled", "d9/d3c/structgalaxy_1_1flags_1_1Enabled.html", null ],
    [ "std::error_category", null, null ],
    [ "std::error_code", null, null ],
    [ "std::error_condition", null, null ],
    [ "std::exception", null, [
      [ "std::bad_alloc", null, null ],
      [ "std::bad_cast", null, null ],
      [ "std::bad_exception", null, null ],
      [ "std::bad_typeid", null, null ],
      [ "std::ios_base::failure", null, null ],
      [ "std::logic_error", null, [
        [ "std::domain_error", null, null ],
        [ "std::invalid_argument", null, null ],
        [ "std::length_error", null, null ],
        [ "std::out_of_range", null, null ]
      ] ],
      [ "std::runtime_error", null, [
        [ "std::overflow_error", null, null ],
        [ "std::range_error", null, null ],
        [ "std::underflow_error", null, null ]
      ] ]
    ] ],
    [ "galaxy::fs::FileInfo", "d0/de8/structgalaxy_1_1fs_1_1FileInfo.html", null ],
    [ "FileInterface", null, [
      [ "galaxy::ui::RMLFile", "d8/dc6/classgalaxy_1_1ui_1_1RMLFile.html", null ]
    ] ],
    [ "galaxy::graphics::Font", "d1/d70/classgalaxy_1_1graphics_1_1Font.html", null ],
    [ "galaxy::graphics::FontContext", "dd/d7d/classgalaxy_1_1graphics_1_1FontContext.html", null ],
    [ "std::forward_list< T >", null, null ],
    [ "galaxy::graphics::Framebuffer", "df/dc0/classgalaxy_1_1graphics_1_1Framebuffer.html", null ],
    [ "galaxy::utils::Guid", "d2/d4d/classgalaxy_1_1utils_1_1Guid.html", null ],
    [ "std::hash< galaxy::utils::Guid >", "d4/d20/structstd_1_1hash_3_01galaxy_1_1utils_1_1Guid_01_4.html", null ],
    [ "galaxy::graphics::IndexBuffer", "d5/d31/classgalaxy_1_1graphics_1_1IndexBuffer.html", null ],
    [ "galaxy::resource::TextureAtlas::Info", "d2/d56/structgalaxy_1_1resource_1_1TextureAtlas_1_1Info.html", null ],
    [ "galaxy::input::Input", "db/df9/classgalaxy_1_1input_1_1Input.html", null ],
    [ "galaxy::input::InputDevice", "da/def/classgalaxy_1_1input_1_1InputDevice.html", [
      [ "galaxy::input::Clipboard", "db/d0b/classgalaxy_1_1input_1_1Clipboard.html", null ],
      [ "galaxy::input::Cursor", "d5/dc8/classgalaxy_1_1input_1_1Cursor.html", null ],
      [ "galaxy::input::Keyboard", "d9/d50/classgalaxy_1_1input_1_1Keyboard.html", null ],
      [ "galaxy::input::Mouse", "dd/d15/classgalaxy_1_1input_1_1Mouse.html", null ]
    ] ],
    [ "galaxy::graphics::InstanceBuffer", "d7/d34/classgalaxy_1_1graphics_1_1InstanceBuffer.html", null ],
    [ "std::ios_base", null, [
      [ "std::basic_ios< char >", null, null ],
      [ "std::basic_ios< wchar_t >", null, null ],
      [ "std::basic_ios< Char >", null, [
        [ "std::basic_istream< char >", null, null ],
        [ "std::basic_istream< wchar_t >", null, null ],
        [ "std::basic_ostream< char >", null, null ],
        [ "std::basic_ostream< wchar_t >", null, null ],
        [ "std::basic_istream< Char >", null, [
          [ "std::basic_ifstream< char >", null, null ],
          [ "std::basic_ifstream< wchar_t >", null, null ],
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_istringstream< char >", null, null ],
          [ "std::basic_istringstream< wchar_t >", null, null ],
          [ "std::basic_ifstream< Char >", null, [
            [ "std::ifstream", null, null ],
            [ "std::wifstream", null, null ]
          ] ],
          [ "std::basic_iostream< Char >", null, [
            [ "std::basic_fstream< char >", null, null ],
            [ "std::basic_fstream< wchar_t >", null, null ],
            [ "std::basic_stringstream< char >", null, null ],
            [ "std::basic_stringstream< wchar_t >", null, null ],
            [ "std::basic_fstream< Char >", null, [
              [ "std::fstream", null, null ],
              [ "std::wfstream", null, null ]
            ] ],
            [ "std::basic_stringstream< Char >", null, [
              [ "std::stringstream", null, null ],
              [ "std::wstringstream", null, null ]
            ] ]
          ] ],
          [ "std::basic_istringstream< Char >", null, [
            [ "std::istringstream", null, null ],
            [ "std::wistringstream", null, null ]
          ] ],
          [ "std::istream", null, null ],
          [ "std::wistream", null, null ]
        ] ],
        [ "std::basic_ostream< Char >", null, [
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_ofstream< char >", null, null ],
          [ "std::basic_ofstream< wchar_t >", null, null ],
          [ "std::basic_ostringstream< char >", null, null ],
          [ "std::basic_ostringstream< wchar_t >", null, null ],
          [ "std::basic_iostream< Char >", null, null ],
          [ "std::basic_ofstream< Char >", null, [
            [ "std::ofstream", null, null ],
            [ "std::wofstream", null, null ]
          ] ],
          [ "std::basic_ostringstream< Char >", null, [
            [ "std::ostringstream", null, null ],
            [ "std::wostringstream", null, null ]
          ] ],
          [ "std::ostream", null, null ],
          [ "std::wostream", null, null ]
        ] ],
        [ "std::ios", null, null ],
        [ "std::wios", null, null ]
      ] ]
    ] ],
    [ "std::wstring::iterator", null, null ],
    [ "std::map< K, T >::iterator", null, null ],
    [ "std::u8string::iterator", null, null ],
    [ "std::unordered_map< K, T >::iterator", null, null ],
    [ "std::multimap< K, T >::iterator", null, null ],
    [ "std::unordered_multimap< K, T >::iterator", null, null ],
    [ "std::u16string::iterator", null, null ],
    [ "std::set< K >::iterator", null, null ],
    [ "std::u32string::iterator", null, null ],
    [ "std::unordered_set< K >::iterator", null, null ],
    [ "std::multiset< K >::iterator", null, null ],
    [ "std::vector< T >::iterator", null, null ],
    [ "std::basic_string_view< Char >::iterator", null, null ],
    [ "std::array< T >::iterator", null, null ],
    [ "std::span< T >::iterator", null, null ],
    [ "std::string_view::iterator", null, null ],
    [ "std::wstring_view::iterator", null, null ],
    [ "std::u8string_view::iterator", null, null ],
    [ "std::u16string_view::iterator", null, null ],
    [ "std::basic_string< Char >::iterator", null, null ],
    [ "std::u32string_view::iterator", null, null ],
    [ "std::deque< T >::iterator", null, null ],
    [ "std::string::iterator", null, null ],
    [ "std::list< T >::iterator", null, null ],
    [ "std::unordered_multiset< K >::iterator", null, null ],
    [ "std::forward_list< T >::iterator", null, null ],
    [ "std::jthread", null, null ],
    [ "galaxy::events::KeyChar", "dc/d97/structgalaxy_1_1events_1_1KeyChar.html", null ],
    [ "galaxy::events::KeyDown", "d7/d91/structgalaxy_1_1events_1_1KeyDown.html", null ],
    [ "galaxy::events::KeyRepeat", "d5/d05/structgalaxy_1_1events_1_1KeyRepeat.html", null ],
    [ "galaxy::events::KeyUp", "d1/d16/structgalaxy_1_1events_1_1KeyUp.html", null ],
    [ "galaxy::resource::Language", "db/dc3/classgalaxy_1_1resource_1_1Language.html", null ],
    [ "galaxy::scene::LayerRegistry", "db/d37/classgalaxy_1_1scene_1_1LayerRegistry.html", null ],
    [ "std::list< T >", null, null ],
    [ "galaxy::core::Loading", "d6/d1e/classgalaxy_1_1core_1_1Loading.html", null ],
    [ "std::lock_guard< T >", null, null ],
    [ "galaxy::error::Log", "d6/d5b/classgalaxy_1_1error_1_1Log.html", null ],
    [ "std::map< K, T >", null, null ],
    [ "galaxy::events::MouseMoved", "db/da7/structgalaxy_1_1events_1_1MouseMoved.html", null ],
    [ "galaxy::events::MousePressed", "d5/d15/structgalaxy_1_1events_1_1MousePressed.html", null ],
    [ "galaxy::events::MouseReleased", "dc/d78/structgalaxy_1_1events_1_1MouseReleased.html", null ],
    [ "galaxy::events::MouseWheel", "d6/d70/structgalaxy_1_1events_1_1MouseWheel.html", null ],
    [ "std::multimap< K, T >", null, null ],
    [ "std::multiset< K >", null, null ],
    [ "std::mutex", null, null ],
    [ "galaxy::graphics::PostEffect", "d0/dd9/classgalaxy_1_1graphics_1_1PostEffect.html", [
      [ "galaxy::graphics::Sharpen", "de/d9e/classgalaxy_1_1graphics_1_1Sharpen.html", null ],
      [ "galaxy::graphics::SMAA", "d7/d53/classgalaxy_1_1graphics_1_1SMAA.html", null ]
    ] ],
    [ "galaxy::graphics::PostProcess", "d8/d69/classgalaxy_1_1graphics_1_1PostProcess.html", null ],
    [ "galaxy::core::Prefab", "d2/d2b/structgalaxy_1_1core_1_1Prefab.html", null ],
    [ "galaxy::components::Primitive::PrimitiveData", "d7/ddc/structgalaxy_1_1components_1_1Primitive_1_1PrimitiveData.html", null ],
    [ "std::priority_queue< T >", null, null ],
    [ "Gfx::ProgramData", "d8/d9d/structGfx_1_1ProgramData.html", null ],
    [ "std::queue< T >", null, null ],
    [ "galaxy::graphics::Rect< Type >", "d4/d0a/classgalaxy_1_1graphics_1_1Rect.html", null ],
    [ "galaxy::algorithm::RectPack", "d5/d99/classgalaxy_1_1algorithm_1_1RectPack.html", null ],
    [ "std::recursive_mutex", null, null ],
    [ "std::recursive_timed_mutex", null, null ],
    [ "galaxy::graphics::Renderable", "d3/db6/classgalaxy_1_1graphics_1_1Renderable.html", [
      [ "galaxy::components::Map", "d3/d19/classgalaxy_1_1components_1_1Map.html", null ],
      [ "galaxy::components::Primitive", "dc/d90/classgalaxy_1_1components_1_1Primitive.html", null ],
      [ "galaxy::components::Sprite", "d4/d86/classgalaxy_1_1components_1_1Sprite.html", null ],
      [ "galaxy::components::Text", "d2/d81/classgalaxy_1_1components_1_1Text.html", null ]
    ] ],
    [ "galaxy::graphics::Renderer", "df/d20/classgalaxy_1_1graphics_1_1Renderer.html", null ],
    [ "RenderInterface", null, [
      [ "galaxy::ui::RMLRenderer", "dc/d67/classgalaxy_1_1ui_1_1RMLRenderer.html", null ]
    ] ],
    [ "galaxy::graphics::RenderTexture", "d8/d85/classgalaxy_1_1graphics_1_1RenderTexture.html", null ],
    [ "std::map< K, T >::reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::reverse_iterator", null, null ],
    [ "std::wstring::reverse_iterator", null, null ],
    [ "std::unordered_set< K >::reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::reverse_iterator", null, null ],
    [ "std::u8string::reverse_iterator", null, null ],
    [ "std::multimap< K, T >::reverse_iterator", null, null ],
    [ "std::u8string_view::reverse_iterator", null, null ],
    [ "std::set< K >::reverse_iterator", null, null ],
    [ "std::u16string::reverse_iterator", null, null ],
    [ "std::multiset< K >::reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::reverse_iterator", null, null ],
    [ "std::u32string::reverse_iterator", null, null ],
    [ "std::array< T >::reverse_iterator", null, null ],
    [ "std::basic_string_view< Char >::reverse_iterator", null, null ],
    [ "std::vector< T >::reverse_iterator", null, null ],
    [ "std::string_view::reverse_iterator", null, null ],
    [ "std::span< T >::reverse_iterator", null, null ],
    [ "std::wstring_view::reverse_iterator", null, null ],
    [ "std::u16string_view::reverse_iterator", null, null ],
    [ "std::u32string_view::reverse_iterator", null, null ],
    [ "std::basic_string< Char >::reverse_iterator", null, null ],
    [ "std::deque< T >::reverse_iterator", null, null ],
    [ "std::string::reverse_iterator", null, null ],
    [ "std::list< T >::reverse_iterator", null, null ],
    [ "std::forward_list< T >::reverse_iterator", null, null ],
    [ "galaxy::ui::RMLEvents", "de/d6f/classgalaxy_1_1ui_1_1RMLEvents.html", null ],
    [ "galaxy::ui::RMLInput", "df/d1c/classgalaxy_1_1ui_1_1RMLInput.html", null ],
    [ "galaxy::fs::Serializable", "d2/d54/classgalaxy_1_1fs_1_1Serializable.html", [
      [ "galaxy::components::Animated", "da/d18/classgalaxy_1_1components_1_1Animated.html", null ],
      [ "galaxy::components::DrawShader", "d2/d46/classgalaxy_1_1components_1_1DrawShader.html", null ],
      [ "galaxy::components::Flag", "d7/dc7/classgalaxy_1_1components_1_1Flag.html", null ],
      [ "galaxy::components::Primitive", "dc/d90/classgalaxy_1_1components_1_1Primitive.html", null ],
      [ "galaxy::components::RigidBody", "df/dfe/classgalaxy_1_1components_1_1RigidBody.html", null ],
      [ "galaxy::components::Script", "db/d40/classgalaxy_1_1components_1_1Script.html", null ],
      [ "galaxy::components::Sprite", "d4/d86/classgalaxy_1_1components_1_1Sprite.html", null ],
      [ "galaxy::components::Tag", "d8/d96/classgalaxy_1_1components_1_1Tag.html", null ],
      [ "galaxy::components::Text", "d2/d81/classgalaxy_1_1components_1_1Text.html", null ],
      [ "galaxy::components::Transform", "d8/d8a/classgalaxy_1_1components_1_1Transform.html", null ],
      [ "galaxy::core::World", "da/dc8/classgalaxy_1_1core_1_1World.html", null ],
      [ "galaxy::graphics::Animation", "da/d19/classgalaxy_1_1graphics_1_1Animation.html", null ],
      [ "galaxy::graphics::Camera", "d7/d9a/classgalaxy_1_1graphics_1_1Camera.html", null ],
      [ "galaxy::graphics::Frame", "de/d57/classgalaxy_1_1graphics_1_1Frame.html", null ],
      [ "galaxy::scene::Layer", "d2/d25/classgalaxy_1_1scene_1_1Layer.html", [
        [ "galaxy::scene::RuntimeLayer", "df/d22/classgalaxy_1_1scene_1_1RuntimeLayer.html", null ],
        [ "galaxy::scene::UILayer", "d3/d20/classgalaxy_1_1scene_1_1UILayer.html", null ]
      ] ],
      [ "galaxy::scene::Layers", "d2/d3a/classgalaxy_1_1scene_1_1Layers.html", null ],
      [ "galaxy::scene::Scene", "dd/d72/classgalaxy_1_1scene_1_1Scene.html", null ],
      [ "galaxy::scene::SceneManager", "d4/d92/classgalaxy_1_1scene_1_1SceneManager.html", null ]
    ] ],
    [ "galaxy::core::ServiceLocator< Service >", "d0/dbf/classgalaxy_1_1core_1_1ServiceLocator.html", null ],
    [ "std::set< K >", null, null ],
    [ "galaxy::graphics::Shader", "d9/d1b/classgalaxy_1_1graphics_1_1Shader.html", null ],
    [ "Gfx::ShadersData", "d2/d93/structGfx_1_1ShadersData.html", null ],
    [ "std::shared_lock< T >", null, null ],
    [ "std::shared_mutex", null, null ],
    [ "std::shared_ptr< T >", null, null ],
    [ "std::shared_ptr< galaxy::graphics::Font >", null, null ],
    [ "std::shared_ptr< galaxy::graphics::PostEffect >", null, null ],
    [ "std::shared_ptr< galaxy::graphics::Shader >", null, null ],
    [ "std::shared_ptr< galaxy::scene::Scene >", null, null ],
    [ "std::shared_ptr< Layer >", null, null ],
    [ "std::shared_ptr< systems::System >", null, null ],
    [ "std::shared_ptr< tson::Map >", null, null ],
    [ "std::shared_timed_mutex", null, null ],
    [ "galaxy::resource::TextureAtlas::Sheet", "d8/d13/structgalaxy_1_1resource_1_1TextureAtlas_1_1Sheet.html", null ],
    [ "galaxy::error::Sink", "d6/d9f/classgalaxy_1_1error_1_1Sink.html", [
      [ "galaxy::error::ConsoleSink", "dc/daf/classgalaxy_1_1error_1_1ConsoleSink.html", null ],
      [ "galaxy::error::FileSink", "de/d18/classgalaxy_1_1error_1_1FileSink.html", null ]
    ] ],
    [ "std::smart_ptr< T >", null, null ],
    [ "galaxy::audio::Sound", "da/ddd/classgalaxy_1_1audio_1_1Sound.html", null ],
    [ "std::span< T >", null, null ],
    [ "galaxy::graphics::SpriteBatch", "dc/d18/classgalaxy_1_1graphics_1_1SpriteBatch.html", null ],
    [ "std::stack< T >", null, null ],
    [ "std::stack< State *, std::vector< State * > >", null, null ],
    [ "galaxy::state::State", "db/d6a/classgalaxy_1_1state_1_1State.html", null ],
    [ "galaxy::state::StateMachine", "d9/d5c/classgalaxy_1_1state_1_1StateMachine.html", null ],
    [ "galaxy::platform::Subprocess", "de/d02/classgalaxy_1_1platform_1_1Subprocess.html", null ],
    [ "galaxy::systems::System", "d9/de7/classgalaxy_1_1systems_1_1System.html", [
      [ "galaxy::systems::AnimationSystem", "d5/d63/classgalaxy_1_1systems_1_1AnimationSystem.html", null ],
      [ "galaxy::systems::PhysicsSystem", "df/da4/classgalaxy_1_1systems_1_1PhysicsSystem.html", null ],
      [ "galaxy::systems::RenderSystem", "d9/d0d/classgalaxy_1_1systems_1_1RenderSystem.html", null ],
      [ "galaxy::systems::ScriptSystem", "dc/d8b/classgalaxy_1_1systems_1_1ScriptSystem.html", null ]
    ] ],
    [ "std::system_error", null, null ],
    [ "SystemInterface", null, [
      [ "galaxy::ui::RMLSystem", "d5/d99/classgalaxy_1_1ui_1_1RMLSystem.html", null ]
    ] ],
    [ "galaxy::graphics::TexelRegion", "de/df9/classgalaxy_1_1graphics_1_1TexelRegion.html", null ],
    [ "galaxy::graphics::Texture", "dc/d3f/classgalaxy_1_1graphics_1_1Texture.html", null ],
    [ "galaxy::resource::TextureAtlas", "d7/d9c/classgalaxy_1_1resource_1_1TextureAtlas.html", null ],
    [ "std::thread", null, null ],
    [ "galaxy::graphics::TileAnim", "d9/de4/classgalaxy_1_1graphics_1_1TileAnim.html", null ],
    [ "galaxy::core::TiledMap", "dd/daa/classgalaxy_1_1core_1_1TiledMap.html", null ],
    [ "std::timed_mutex", null, null ],
    [ "galaxy::async::Timer", "da/d6d/classgalaxy_1_1async_1_1Timer.html", null ],
    [ "galaxy::async::TimerAsync", "d6/d7f/classgalaxy_1_1async_1_1TimerAsync.html", null ],
    [ "galaxy::graphics::UniformBuffer", "d8/d6a/classgalaxy_1_1graphics_1_1UniformBuffer.html", null ],
    [ "galaxy::graphics::UniformInfo", "d2/d30/structgalaxy_1_1graphics_1_1UniformInfo.html", null ],
    [ "std::unique_lock< T >", null, null ],
    [ "std::unique_ptr< T >", null, null ],
    [ "std::unique_ptr< b2World >", null, null ],
    [ "std::unique_ptr< galaxy::error::Sink >", null, null ],
    [ "std::unique_ptr< galaxy::graphics::UniformBuffer >", null, null ],
    [ "std::unique_ptr< Service >", null, null ],
    [ "std::unordered_map< K, T >", null, null ],
    [ "std::unordered_multimap< K, T >", null, null ],
    [ "std::unordered_multiset< K >", null, null ],
    [ "std::unordered_set< K >", null, null ],
    [ "std::valarray< T >", null, null ],
    [ "std::vector< T >", null, null ],
    [ "std::vector< entt::entity >", null, null ],
    [ "std::vector< galaxy::graphics::Frame >", null, null ],
    [ "std::vector< galaxy::graphics::Rect >", null, null ],
    [ "std::vector< galaxy::graphics::Renderable * >", null, null ],
    [ "std::vector< galaxy::graphics::Vertex >", null, null ],
    [ "std::vector< galaxy::resource::TextureAtlas::Sheet >", null, null ],
    [ "std::vector< glm::vec2 >", null, null ],
    [ "std::vector< std::pair< galaxy::components::RigidBody *, galaxy::components::Transform * > >", null, null ],
    [ "std::vector< std::pair< unsigned int, unsigned int > >", null, null ],
    [ "std::vector< std::shared_ptr< galaxy::graphics::PostEffect > >", null, null ],
    [ "std::vector< std::shared_ptr< Layer > >", null, null ],
    [ "std::vector< std::shared_ptr< systems::System > >", null, null ],
    [ "std::vector< std::string >", null, null ],
    [ "std::vector< std::type_index >", null, null ],
    [ "std::vector< std::unique_ptr< galaxy::error::Sink > >", null, null ],
    [ "std::vector< unsigned int >", null, null ],
    [ "std::vector< Variant >", null, null ],
    [ "galaxy::graphics::Vertex", "d9/d6c/classgalaxy_1_1graphics_1_1Vertex.html", null ],
    [ "galaxy::graphics::VertexArray", "df/dc0/classgalaxy_1_1graphics_1_1VertexArray.html", null ],
    [ "galaxy::graphics::VertexBuffer", "d3/d4b/classgalaxy_1_1graphics_1_1VertexBuffer.html", null ],
    [ "galaxy::fs::VirtualFileSystem", "d4/de8/classgalaxy_1_1fs_1_1VirtualFileSystem.html", null ],
    [ "std::weak_ptr< T >", null, null ],
    [ "galaxy::core::Window", "d5/d25/classgalaxy_1_1core_1_1Window.html", null ],
    [ "galaxy::events::WindowResized", "d9/dd9/structgalaxy_1_1events_1_1WindowResized.html", null ],
    [ "galaxy::core::WindowSettings", "d1/dfa/structgalaxy_1_1core_1_1WindowSettings.html", null ],
    [ "galaxy::algorithm::ZLib", "d2/d05/classgalaxy_1_1algorithm_1_1ZLib.html", null ],
    [ "K", null, null ],
    [ "T", null, null ],
    [ "Type", null, null ]
];