var hierarchy =
[
    [ "galaxy::core::App", "d5/d5a/classgalaxy_1_1core_1_1App.html", null ],
    [ "galaxy::media::AudioEngine< type >", "d0/d0d/classgalaxy_1_1media_1_1AudioEngine.html", null ],
    [ "galaxy::resource::Cache< Resource, Loader >", "da/d64/classgalaxy_1_1resource_1_1Cache.html", null ],
    [ "galaxy::input::CameraController", "d0/d15/classgalaxy_1_1input_1_1CameraController.html", null ],
    [ "galaxy::core::Config", "d6/de9/classgalaxy_1_1core_1_1Config.html", null ],
    [ "galaxy::events::ContentScale", "d8/d2a/structgalaxy_1_1events_1_1ContentScale.html", null ],
    [ "galaxy::flags::DenySerialization", "da/d36/classgalaxy_1_1flags_1_1DenySerialization.html", null ],
    [ "galaxy::meta::EntityMeta", "db/db8/classgalaxy_1_1meta_1_1EntityMeta.html", null ],
    [ "galaxy::utils::Guid", "d2/d4d/classgalaxy_1_1utils_1_1Guid.html", null ],
    [ "std::hash< galaxy::utils::Guid >", "d4/d20/structstd_1_1hash_3_01galaxy_1_1utils_1_1Guid_01_4.html", null ],
    [ "galaxy::resource::TextureAtlas::Info", "d2/d56/structgalaxy_1_1resource_1_1TextureAtlas_1_1Info.html", null ],
    [ "galaxy::events::KeyChar", "dc/d97/structgalaxy_1_1events_1_1KeyChar.html", null ],
    [ "galaxy::events::KeyPress", "d0/d92/structgalaxy_1_1events_1_1KeyPress.html", null ],
    [ "galaxy::events::KeyRepeat", "d5/d05/structgalaxy_1_1events_1_1KeyRepeat.html", null ],
    [ "galaxy::core::Loader", "dd/ddf/classgalaxy_1_1core_1_1Loader.html", null ],
    [ "galaxy::resource::Loader< Resource >", "d0/d02/structgalaxy_1_1resource_1_1Loader.html", null ],
    [ "galaxy::resource::Loader< media::Sound >", "d0/d02/structgalaxy_1_1resource_1_1Loader.html", [
      [ "galaxy::resource::MusicLoader", "d7/d3e/structgalaxy_1_1resource_1_1MusicLoader.html", null ],
      [ "galaxy::resource::SoundLoader", "d2/d43/structgalaxy_1_1resource_1_1SoundLoader.html", null ],
      [ "galaxy::resource::VoiceLoader", "db/de5/structgalaxy_1_1resource_1_1VoiceLoader.html", null ]
    ] ],
    [ "galaxy::logging::Log", "d9/dec/classgalaxy_1_1logging_1_1Log.html", null ],
    [ "galaxy::logging::LogMessage", "d1/db0/structgalaxy_1_1logging_1_1LogMessage.html", null ],
    [ "galaxy::map::Map", "df/d2b/classgalaxy_1_1map_1_1Map.html", null ],
    [ "galaxy::events::MouseEnter", "d0/d34/structgalaxy_1_1events_1_1MouseEnter.html", null ],
    [ "galaxy::events::MouseMoved", "db/da7/structgalaxy_1_1events_1_1MouseMoved.html", null ],
    [ "galaxy::events::MousePressed", "d5/d15/structgalaxy_1_1events_1_1MousePressed.html", null ],
    [ "galaxy::events::MouseReleased", "dc/d78/structgalaxy_1_1events_1_1MouseReleased.html", null ],
    [ "galaxy::events::MouseWheel", "d6/d70/structgalaxy_1_1events_1_1MouseWheel.html", null ],
    [ "galaxy::core::Prefab", "d6/d40/classgalaxy_1_1core_1_1Prefab.html", null ],
    [ "galaxy::math::Random", "d9/deb/classgalaxy_1_1math_1_1Random.html", null ],
    [ "galaxy::math::RectPack", "d3/d76/classgalaxy_1_1math_1_1RectPack.html", null ],
    [ "galaxy::core::Registry", "de/d2c/classgalaxy_1_1core_1_1Registry.html", null ],
    [ "galaxy::media::RingBuffer", "d5/df7/classgalaxy_1_1media_1_1RingBuffer.html", null ],
    [ "galaxy::lua::Script", "d5/d4a/classgalaxy_1_1lua_1_1Script.html", null ],
    [ "galaxy::fs::Serializable", "d2/d54/classgalaxy_1_1fs_1_1Serializable.html", [
      [ "galaxy::components::Animated", "da/d18/classgalaxy_1_1components_1_1Animated.html", null ],
      [ "galaxy::components::Circle", "da/d0d/classgalaxy_1_1components_1_1Circle.html", null ],
      [ "galaxy::components::Ellipse", "d9/ddf/classgalaxy_1_1components_1_1Ellipse.html", null ],
      [ "galaxy::components::Point", "d4/d0e/classgalaxy_1_1components_1_1Point.html", null ],
      [ "galaxy::components::Polygon", "d0/dbe/classgalaxy_1_1components_1_1Polygon.html", null ],
      [ "galaxy::components::Polyline", "dd/d2d/classgalaxy_1_1components_1_1Polyline.html", null ],
      [ "galaxy::components::RigidBody", "df/dfe/classgalaxy_1_1components_1_1RigidBody.html", null ],
      [ "galaxy::components::Script", "db/d40/classgalaxy_1_1components_1_1Script.html", null ],
      [ "galaxy::components::Sprite", "d4/d86/classgalaxy_1_1components_1_1Sprite.html", null ],
      [ "galaxy::components::Tag", "d8/d96/classgalaxy_1_1components_1_1Tag.html", null ],
      [ "galaxy::components::Text", "d2/d81/classgalaxy_1_1components_1_1Text.html", null ],
      [ "galaxy::components::Transform", "d8/d8a/classgalaxy_1_1components_1_1Transform.html", null ],
      [ "galaxy::flags::Disabled", "d3/d72/classgalaxy_1_1flags_1_1Disabled.html", null ],
      [ "galaxy::scene::Scene", "dd/d72/classgalaxy_1_1scene_1_1Scene.html", null ],
      [ "galaxy::scene::SceneManager", "d4/d92/classgalaxy_1_1scene_1_1SceneManager.html", null ]
    ] ],
    [ "galaxy::meta::EntityMeta::SerializationData", "d6/d90/structgalaxy_1_1meta_1_1EntityMeta_1_1SerializationData.html", null ],
    [ "galaxy::settings", "d1/db3/structgalaxy_1_1settings.html", null ],
    [ "galaxy::resource::TextureAtlas::Sheet", "d8/d13/structgalaxy_1_1resource_1_1TextureAtlas_1_1Sheet.html", null ],
    [ "galaxy::logging::Sink", "d9/d9f/classgalaxy_1_1logging_1_1Sink.html", [
      [ "galaxy::logging::ConsoleSink", "d9/dce/classgalaxy_1_1logging_1_1ConsoleSink.html", null ],
      [ "galaxy::logging::FileSink", "d6/d7a/classgalaxy_1_1logging_1_1FileSink.html", null ]
    ] ],
    [ "galaxy::media::Sound", "d6/dd5/classgalaxy_1_1media_1_1Sound.html", null ],
    [ "galaxy::state::State", "db/d6a/classgalaxy_1_1state_1_1State.html", null ],
    [ "galaxy::state::StateMachine", "d9/d5c/classgalaxy_1_1state_1_1StateMachine.html", null ],
    [ "galaxy::platform::Subprocess", "de/d02/classgalaxy_1_1platform_1_1Subprocess.html", null ],
    [ "galaxy::systems::System", "d9/de7/classgalaxy_1_1systems_1_1System.html", [
      [ "galaxy::systems::AnimationSystem", "d5/d63/classgalaxy_1_1systems_1_1AnimationSystem.html", null ],
      [ "galaxy::systems::PhysicsSystem", "df/da4/classgalaxy_1_1systems_1_1PhysicsSystem.html", null ],
      [ "galaxy::systems::RenderSystem", "d9/d0d/classgalaxy_1_1systems_1_1RenderSystem.html", null ],
      [ "galaxy::systems::ScriptSystem", "dc/d8b/classgalaxy_1_1systems_1_1ScriptSystem.html", null ]
    ] ],
    [ "galaxy::resource::TextureAtlas", "d7/d9c/classgalaxy_1_1resource_1_1TextureAtlas.html", null ],
    [ "galaxy::components::TileMap", "d2/db4/classgalaxy_1_1components_1_1TileMap.html", null ],
    [ "galaxy::async::Timer< async >", "da/d6d/classgalaxy_1_1async_1_1Timer.html", null ],
    [ "galaxy::media::Video", "de/d0b/classgalaxy_1_1media_1_1Video.html", null ],
    [ "galaxy::fs::VirtualFileSystem", "d4/de8/classgalaxy_1_1fs_1_1VirtualFileSystem.html", null ],
    [ "galaxy::core::Window", "d5/d25/classgalaxy_1_1core_1_1Window.html", null ],
    [ "galaxy::events::WindowClosed", "dc/dad/structgalaxy_1_1events_1_1WindowClosed.html", null ],
    [ "galaxy::events::WindowResized", "d9/dd9/structgalaxy_1_1events_1_1WindowResized.html", null ],
    [ "galaxy::map::World", "d9/d75/classgalaxy_1_1map_1_1World.html", null ],
    [ "galaxy::math::ZLib", "d1/dc9/classgalaxy_1_1math_1_1ZLib.html", null ]
];