name: linux

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Test Repo
      shell: bash
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test

    - name: Remove Old CMake
      shell: bash
      run: sudo apt purge --auto-remove cmake

    - name: Update APT
      shell: bash
      run: sudo apt update
    
    - name: Install Dependencies
      shell: bash
      run: sudo apt install git g++ clang llvm libc++-dev make pip libfreetype-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev libglu1-mesa-dev
    
    - name: Install CMake
      shell: bash
      run: pip install cmake
   
    - name: Export PATH
      shell: bash
      run: export PATH="~/.local/bin:$PATH"
    
    - name: Export CC
      shell: bash
      run: export CC=/usr/bin/clang
    
    - name: Export CXX
      shell: bash
      run: export CXX=/usr/bin/clang++
    
    - name: Checkout Master
      shell: bash
      run: git clone --recursive https://github.com/DomRe/galaxy.git galaxy_engine
    
    - name: Enter Repo
      shell: bash
      run: cd galaxy_engine

    - name: Checkout Submodules
      shell: bash
      run: git submodule update --init --recursive

    - name: Configure Build Files
      shell: bash
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DENABLE_DOXYGEN=OFF -Bbuild -H.

    - name: Enter Build Directory
      shell: bash
      run: cd build

    - name: Build
      shell: bash
      run: make all
