set(GALAXY_PREPROCESSOR_FLAGS
    "IMGUI_IMPL_OPENGL_LOADER_GLAD"
    "UNICODE"
    "_UNICODE"
    "AL_LIBTYPE_STATIC"
    "GLM_FORCE_XYZW_ONLY"
    "GLFW_INCLUDE_NONE"
    "STB_IMAGE_IMPLEMENTATION"
    "STB_IMAGE_WRITE_IMPLEMENTATION"
    "STB_IMAGE_RESIZE_IMPLEMENTATION"
    "STBI_ONLY_PNG"
    "STB_IMAGE_STATIC"
    "STB_IMAGE_WRITE_STATIC"
    "STB_IMAGE_RESIZE_STATIC"
    "SOL_CXX17_FEATURES"
    "SOL_ALL_SAFETIES_ON"
    "_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS"
)

set(GALAXY_PREPROCESSOR_FLAGS_DEBUG_GENERAL
    "${GALAXY_PREPROCESSOR_FLAGS}"
    "_DEBUG"
)

set(GALAXY_PREPROCESSOR_FLAGS_RELEASE_GENERAL
    "${GALAXY_PREPROCESSOR_FLAGS}"
    "NDEBUG"
)

if (MSVC)
    set (WINDOWS_FLAGS
        "WIN32"
        "_WIN32"
        "WIN64"
        "_WIN64"
        "_WINDOWS"
        "NOMINMAX"
        "WIN32_LEAN_AND_MEAN"
        "_CRT_SECURE_NO_WARNINGS"
        "_CRT_SECURE_NO_DEPRECATE"
        "_CRT_NONSTDC_NO_DEPRECATE"
    )

    set(GALAXY_PREPROCESSOR_FLAGS_DEBUG 
        "${GALAXY_PREPROCESSOR_FLAGS_DEBUG_GENERAL}"
        "${WINDOWS_FLAGS}"
    )

    set(GALAXY_PREPROCESSOR_FLAGS_RELEASE
        "${GALAXY_PREPROCESSOR_FLAGS_RELEASE_GENERAL}"
        "${WINDOWS_FLAGS}"
    )
else()
    set(UNIX_FLAGS
        "_GLIBCXX_HAS_GTHREADS"
        "_GLIBCXX_USE_NANOSLEEP"
        "_LIBCPP_ENABLE_NODISCARD"
        "_LIBCPP_DISABLE_DEPRECATION_WARNINGS"
        "AUTO_DOWNLOAD=0"
        "HAS_REMOTE_API=0"
        "USE_OS_TZDB=1"
    )

    set(GALAXY_PREPROCESSOR_FLAGS_DEBUG 
        "${GALAXY_PREPROCESSOR_FLAGS_DEBUG_GENERAL}"
        "${UNIX_FLAGS}"
        "_LIBCPP_DEBUG"
        "_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS"
    )

    set(GALAXY_PREPROCESSOR_FLAGS_RELEASE
        "${GALAXY_PREPROCESSOR_FLAGS_RELEASE_GENERAL}"
        "${UNIX_FLAGS}"
    )
endif()