set (WINDOWS_FLAGS
    "WIN32"
    "_WIN32"
    "WIN64"
    "_WIN64"
    "WIN32_LEAN_AND_MEAN"
    "NOMINMAX"
    "UNICODE"
    "_UNICODE"
    "_CRT_SECURE_NO_WARNINGS"
    "_CRT_SECURE_NO_DEPRECATE"
    "_CRT_NONSTDC_NO_DEPRECATE"
)

set(GALAXY_PREPROCESSOR_FLAGS
    "IMGUI_IMPL_OPENGL_LOADER_GLAD"
    "AL_LIBTYPE_STATIC"
    "GLM_FORCE_XYZW_ONLY"
    "GLM_FORCE_CTOR_INIT"
    "GLFW_INCLUDE_NONE"
    "STB_IMAGE_IMPLEMENTATION"
    "STB_IMAGE_WRITE_IMPLEMENTATION"
    "STB_IMAGE_RESIZE_IMPLEMENTATION"
    "STBI_ONLY_PNG"
    "STB_IMAGE_STATIC"
    "STB_IMAGE_WRITE_STATIC"
    "STB_IMAGE_RESIZE_STATIC"
    "SOL_CXX17_FEATURES"
    "SOL_ALL_SAFETIES_ON"
    "_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS"
    "${WINDOWS_FLAGS}"
)

set(GALAXY_PREPROCESSOR_FLAGS_DEBUG
    "${GALAXY_PREPROCESSOR_FLAGS}"
    "_DEBUG"
    "_CONSOLE"
)

set(GALAXY_PREPROCESSOR_FLAGS_RELEASE
    "${GALAXY_PREPROCESSOR_FLAGS}"
    "NDEBUG"
    "_WINDOWS"
)