name: linux

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update APT
      shell: bash
      run: sudo apt update
    
    - name: Install Dependencies
      shell: bash
      run: sudo apt install git g++ clang llvm libc++-dev make pip libfreetype-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev libglu1-mesa-dev
    
    - name: Checkout Master
      shell: bash
      run: git clone --recursive https://github.com/DomRe/galaxy.git galaxy
    
    - name: Enter Repo
      shell: bash
      run: cd galaxy

    - name: Configure Build Files
      shell: bash
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DENABLE_DOXYGEN=OFF -Bbuild -H.

    - name: Enter Build Directory
      shell: bash
      run: cd build

    - name: Build
      shell: bash
      run: make all
