name: Windows Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          Write-Host "Installing VS 2026 Build Tools..."
          choco install visualstudio2026buildtools `
            --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --quiet" `
            -y --ignore-package-exit-codes=3010
          Write-Host "VS 2026 Build Tools installation completed" 

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[18.1.1]'

      - name: Build solution
        run: msbuild galaxy.sln /p:Configuration=Release /p:Platform=x64
